export const SET_DAY: string = 'SET_DAY'
export const NEW_HABIT: string = 'NEW_HABIT'
export const RESET_STATE: string = 'RESET_STATE'
export const SET_TASKS: string = 'SET_TASKS'
export const COMPLETE_TASK: string = 'COMPLETE_TASK'
export const DELETE_TASK: string = 'DELETE_TASK'
export const CREATE_TASK: string = 'CREATE_TASK'
export const EDIT_TASK: string = 'EDIT_TASK'
